/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.com.hiromi00.sistema.gui;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Calendar;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import mx.com.hiromi00.sistema.database.BaseDatos;
import mx.com.hiromi00.sistema.pojo.DetalleVenta;
import mx.com.hiromi00.sistema.pojo.Producto;
import mx.com.hiromi00.sistema.pojo.Venta;

/**
 *
 * @author cesar
 */
public class VentasFrame extends javax.swing.JInternalFrame {

    //Se requiere editar un método del modeloTablaProd para que no se puedan editar los objetos de la tabla
    DefaultTableModel modeloTablaProd = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int coumn){
            return false;
        }
    };
    DefaultListModel <Producto> modeloListaProd = new DefaultListModel<>();
    BaseDatos database = new BaseDatos();
    /**
     * Creates new form Ventas
     */
    public VentasFrame() {
        initComponents();
        cargarColumnasTabla();
        cargarListenerModeloTabla();
        
    }
    
    //Método que carga todos los importes en el total
    private void cargarListenerModeloTabla(){
        //Se crea el listener que modificará los datos del total
        modeloTablaProd.addTableModelListener(new TableModelListener(){
            @Override
            //Se carga el método abstracto para poder realizar dicha función
            public void tableChanged(TableModelEvent evt){
                int numFilas = modeloTablaProd.getRowCount();
                double sumatoria = 0;
                for (int i = 0; i < numFilas; i++){
                    String importe = (String)modeloTablaProd.getValueAt(i, 4);
                    sumatoria += Double.parseDouble(importe);
                }
                lblTotalPagar.setText(String.valueOf(sumatoria));
            }
        });
    }//Fin del método que carga el total

    private void cargarColumnasTabla(){
        modeloTablaProd.addColumn("Clave");
        modeloTablaProd.addColumn("Nombre");
        modeloTablaProd.addColumn("Precio Venta");
        modeloTablaProd.addColumn("Cantidad");
        modeloTablaProd.addColumn("Importe");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscarProd = new javax.swing.JLabel();
        tfBuscarProd = new javax.swing.JTextField();
        spListaProd = new javax.swing.JScrollPane();
        listProd = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProd = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTotalPagar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTipoPago = new javax.swing.JTextField();
        btnVender = new javax.swing.JButton();
        btnCancelarProd = new javax.swing.JButton();
        btnCancelarVenta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblimagen = new javax.swing.JLabel();
        btnCorte = new javax.swing.JButton();

        setTitle("Ventas");
        setPreferredSize(new java.awt.Dimension(1050, 676));

        lblBuscarProd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBuscarProd.setText("Buscar Producto");

        tfBuscarProd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarProdActionPerformed(evt);
            }
        });
        tfBuscarProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBuscarProdKeyReleased(evt);
            }
        });

        listProd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        listProd.setModel(modeloListaProd);
        listProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listProdMousePressed(evt);
            }
        });
        spListaProd.setViewportView(listProd);

        tablaProd.setModel(modeloTablaProd);
        tablaProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaProdKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProd);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Venta Total");

        lblTotalPagar.setFont(new java.awt.Font("Dialog", 1, 72)); // NOI18N
        lblTotalPagar.setForeground(new java.awt.Color(102, 102, 255));
        lblTotalPagar.setText("0.00");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Pago con");

        tfTipoPago.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        tfTipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTipoPagoActionPerformed(evt);
            }
        });

        btnVender.setBackground(new java.awt.Color(0, 102, 0));
        btnVender.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnVender.setForeground(new java.awt.Color(255, 255, 255));
        btnVender.setText("Realizar Venta");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lblTotalPagar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(lblTotalPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        btnCancelarProd.setText("Cancelar Producto");
        btnCancelarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProdActionPerformed(evt);
            }
        });

        btnCancelarVenta.setText("Cancelar Venta");
        btnCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVentaActionPerformed(evt);
            }
        });

        jPanel3.setMinimumSize(new java.awt.Dimension(230, 230));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(230, 230));

        lblimagen.setPreferredSize(new java.awt.Dimension(230, 230));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnCorte.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnCorte.setText("Corte del día");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnCancelarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(158, 158, 158))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfBuscarProd)
                            .addComponent(spListaProd)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBuscarProd)
                                .addGap(168, 168, 168)))
                        .addGap(40, 40, 40)
                        .addComponent(btnCorte)
                        .addGap(106, 106, 106)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1288, 1288, 1288)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblBuscarProd)
                        .addGap(21, 21, 21)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(tfBuscarProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spListaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnCorte)
                                        .addGap(17, 17, 17))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCancelarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                    .addComponent(btnCancelarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarProdActionPerformed

    private void btnCancelarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProdActionPerformed
        int filaSeleccionada = tablaProd.getSelectedRow();
        int cantidadFilas = modeloTablaProd.getRowCount();
        
        if (cantidadFilas > 0){
            int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea borrar este producto?");
            if(opcion == 0){
                modeloTablaProd.removeRow(filaSeleccionada);
            }
        }
    }//GEN-LAST:event_btnCancelarProdActionPerformed

    private void btnCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVentaActionPerformed
        int cantidadFilas = modeloTablaProd.getRowCount();
        if (cantidadFilas > 0){
            int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea cancelar la venta?");
            if(opcion == 0){
                for(int i = cantidadFilas-1; i >= 0; i--){
                    modeloTablaProd.removeRow(i);
                }
            }
        }
    }//GEN-LAST:event_btnCancelarVentaActionPerformed

    private void tfTipoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTipoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTipoPagoActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        
        ArrayList<DetalleVenta> detalles = new ArrayList<>();
        //Se obtiene la sumatoria de las ventas
        String sumatoriaVentas = lblTotalPagar.getText();
        double montoVenta = Double.parseDouble(sumatoriaVentas);
        
        //Se realiza el cambio y efectua el pago
        String pagarStr = tfTipoPago.getText();
        double cambio = 0;
        //Se realiza una condicional que dará el cambio
        if (!pagarStr.isEmpty()){
            double pagar = Double.parseDouble(pagarStr);
            cambio = pagar - montoVenta;
        }
        //Se obtiene la fecha actual junto a la hora
        Calendar calendarioLocal = Calendar.getInstance();
        java.util.Date fechaActual = calendarioLocal.getTime();
        
        //Se crean los milisegundos para dar una fecha precisa y es und ato fundamental
        long fechaMiliseg = fechaActual.getTime();
        //Se usa la libreria de DATE DE SQL
        java.sql.Date fecha = new java.sql.Date(fechaMiliseg);
        
        Venta venta = new Venta(montoVenta,fecha);

        //Se agrega la venta a la base de datos
        Long idVenta = database.insertarVenta(venta);
        
        
        int numRows = modeloTablaProd.getRowCount();
        
        for(int i = 0; i < numRows; i++){
            String idPorducto = (String)modeloTablaProd.getValueAt(i, 0);
            String cantidadStr = (String)modeloTablaProd.getValueAt(i, 3);
            double cantidad = Double.parseDouble(cantidadStr);
            
            DetalleVenta detalle = new DetalleVenta(idVenta, idPorducto, cantidad);
            
            database.insertarDetalleVenta(detalle);
            //Se añaden todos los detalles al arraylist
            detalles.add(detalle);
        }
        //Se borran las filas de la tabla
        for(int i = numRows-1; i >=0; i--){
            modeloTablaProd.removeRow(i);
        }
        lblTotalPagar.setText("0.00");
        
        if(!pagarStr.isEmpty()){
            //Se establece un emsnaje en HTML para hacerlo más estetico
            JOptionPane.showMessageDialog(this, "<html><h1 style = 'font-size: 150 px; color: red'>" + cambio + "</h1></html>", "Usted debe de devolver como cambio: ", 1);
            tfTipoPago.setText("");
        }
    }//GEN-LAST:event_btnVenderActionPerformed

    //Despliega la foto a mostrar en la interfaz
    private void desplegarFoto(Producto prod){
        ImageIcon imagenProd = null;
        try{
            //Obitnee la imagen desde la base de datos
            InputStream isFoto = database.buscarFoto(prod);
            BufferedImage biFoto = ImageIO.read(isFoto);
            imagenProd = new ImageIcon(biFoto);
            Image imageProd = imagenProd.getImage();
            int anchoImg = lblimagen.getWidth();
            int altoImg = lblimagen.getHeight();
            
            Image imgRedimensionada = imageProd.getScaledInstance(anchoImg, altoImg, Image.SCALE_DEFAULT);
            
            ImageIcon iconoRedimensionadao = new ImageIcon(imgRedimensionada);

            lblimagen.setIcon(iconoRedimensionadao);
        }catch(IOException ex){
            ex.printStackTrace();
        }
    }
    
    private void tfBuscarProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarProdKeyReleased
        limpiarListaProductos();
        
        //Comenza la captura de lo introducido en el area "buscar"
        String cadenaBusqueda = tfBuscarProd.getText();
        if (cadenaBusqueda.isEmpty()){
            limpiarListaProductos();
        }
        else{
            ArrayList<Producto> listaProd = database.obtenerProductosPorCriterio(cadenaBusqueda);
        
            for(Producto prod : listaProd){
                modeloListaProd.addElement(prod);
            }
        }
        
    }//GEN-LAST:event_tfBuscarProdKeyReleased

    private void listProdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listProdMousePressed
        //Obtiene el tipo de fuente de dodne se quiere seleccionar el evento
        JList lista = (JList)evt.getSource();
        if(evt.getClickCount() == 2){
            //Obtiene el indice y el producto que se ha seleccionado
            int index = lista.locationToIndex(evt.getPoint());
            Producto prod = (Producto)lista.getSelectedValue();
            //Se añaden los productos a la tabla 
            agregarProductoVenta(prod);
            
            desplegarFoto(prod);
        }
    }//GEN-LAST:event_listProdMousePressed

    private void tablaProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaProdKeyReleased
        //Espera a que se presione la tecla F2
        if (evt.getKeyCode() == KeyEvent.VK_F2){
            int filaSeleccionada = tablaProd.getSelectedRow();
            //Muestra en mensaje pidiendo la cantidad a agregar
            String cantidad = JOptionPane.showInputDialog("Modificar la cantidad: ");
            String precioVenta = (String)modeloTablaProd.getValueAt(filaSeleccionada, 2);
            //Se realiza el importe a pagar haciendo la multiplicación de los objetos
            double importe = Double.parseDouble(cantidad) * Double.parseDouble(precioVenta);
            //Se establece la cantidad escrita
            modeloTablaProd.setValueAt(cantidad, filaSeleccionada, 3);
            //Se establece el importe establecido
            modeloTablaProd.setValueAt(importe, filaSeleccionada, 4);
            
        }
    }//GEN-LAST:event_tablaProdKeyReleased

    private void agregarProductoVenta(Producto prod){
        String claveProd = prod.getIdProducto();
        String nombreProd = prod.getNomProducto();
        String precioVenta = String.valueOf(prod.getPrecioVentaProducto());
        String importe = String.valueOf(prod.getPrecioVentaProducto());
        
        
        //Se crea un arreglo que sostenga todos los datos que se mostrarán en la tabla
        String [] datosProducto = {claveProd, nombreProd, precioVenta, "1", importe};
        //Se le agrega el producto desde el modelo diseñado anteriormente
        modeloTablaProd.addRow(datosProducto);
    }
    //Método que limpia los datos de la lista de articulos
    private void limpiarListaProductos(){
        modeloListaProd.clear();
    }//Fin del método de limpia lista productos

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarProd;
    private javax.swing.JButton btnCancelarVenta;
    private javax.swing.JButton btnCorte;
    private javax.swing.JButton btnVender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarProd;
    private javax.swing.JLabel lblTotalPagar;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JList<Producto> listProd;
    private javax.swing.JScrollPane spListaProd;
    private javax.swing.JTable tablaProd;
    private javax.swing.JTextField tfBuscarProd;
    private javax.swing.JTextField tfTipoPago;
    // End of variables declaration//GEN-END:variables
}
